# Generated by Django 5.1.1 on 2024-09-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
