# Generated by Django 5.1.1 on 2024-09-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0003_alter_pizza_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizza",
            name="price",
            field=models.CharField(max_length=12),
        ),
    ]
