# Generated by Django 5.1.1 on 2025-01-15 11:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0005_alter_pizza_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="address",
        ),
    ]
