# Generated by Django 5.1.1 on 2025-01-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0007_customuser_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                choices=[("Nigeria", "Nigeria")], default="Nigeria", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lagos", "Lagos"),
                    ("Abuja", "Abuja"),
                    ("Ibadan", "Ibadan"),
                    ("Ekiti", "Ekiti"),
                    ("Osun", "Osun"),
                    ("Ogun", "Ogun"),
                    ("Ondo", "Ondo"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
