# Generated by Django 5.1.1 on 2025-01-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0008_customuser_country_customuser_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lagos", "Lagos"),
                    ("Abuja", "Abuja"),
                    ("Oyo", "Oyo"),
                    ("Ekiti", "Ekiti"),
                    ("Osun", "Osun"),
                    ("Ogun", "Ogun"),
                    ("Ondo", "Ondo"),
                ],
                default="None",
                max_length=50,
                null=True,
            ),
        ),
    ]
