# Generated by Django 5.1.1 on 2025-01-22 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0009_alter_customuser_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="state",
        ),
    ]
