# Generated by Django 5.1.1 on 2025-01-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0012_alter_order_billing_address_alter_order_country"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="billing_address",
            new_name="address",
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.ForeignKey(
                blank=True,
                default="Nigeria",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="country_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
