# Generated by Django 5.1.1 on 2025-01-31 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0013_rename_billing_address_order_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address",
            new_name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="state",
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="country_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
