# Generated by Django 5.1.1 on 2025-02-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0014_rename_address_order_billing_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
