# Generated by Django 5.1.1 on 2025-02-01 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0015_remove_order_billing_address_order_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address",
            new_name="billing_address",
        ),
    ]
