# Generated by Django 5.1.1 on 2025-02-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pizzadelivery", "0016_rename_address_order_billing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
